from content_hub.interfaces.compat.legacy_system_init import get_platform_adapter
from content_hub.interfaces.compat.legacy_system_init import initialize_global_tools
from content_hub.interfaces.compat.legacy_system_init import setup_aiwritex
